// Uji browser CMS blog: tulis artikel, pratinjau, terbitkan, unggah sampul, lalu baca di portal publik.
const { chromium } = require('playwright');
const fs = require('fs'), os = require('os'), path = require('path');
const BASE = process.env.BASE || 'http://127.0.0.1:8099';
const OUT = os.tmpdir() + '/';
let pass = 0, fail = 0;
const check = (n, c, x = '') => { if (c) { pass++; console.log('  ok  ', n); } else { fail++; console.log('  FAIL', n, x); } };
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  p.on('dialog', d => d.accept());
  const judul = 'Uji Browser Blog ' + Date.now().toString(36);
  await p.goto(BASE + '/', { waitUntil: 'networkidle' });

  console.log('Portal publik');
  check('menu Blog ada di navigasi atas', await p.locator('.topbar nav [data-go="blog"]').count() === 1);
  check('beranda menampilkan artikel terbaru', await p.locator('.blog-card').count() >= 3);
  await p.click('.topbar nav [data-go="blog"]'); await p.waitForTimeout(600);
  check('halaman blog: artikel utama + kartu', await p.locator('.blog-feat').count() === 1 && await p.locator('.blog-card').count() >= 4);
  await p.fill('#blog-q', 'barista'); await p.press('#blog-q', 'Enter'); await p.waitForTimeout(600);
  check('pencarian artikel', (await p.locator('.blog-card').count()) === 1 && /Barista/.test(await p.locator('.blog-card').innerText()));
  await p.click('[data-x="blogReset"]'); await p.waitForTimeout(500);
  await p.click('[data-x="blogKat"][data-k="Pengumuman"]'); await p.waitForTimeout(600);
  const kats = await p.$$eval('.blog-card .chip.info', els => els.map(e => e.textContent));
  check('filter kategori', kats.length > 0 && kats.every(k => k === 'Pengumuman'));
  await p.click('[data-x="blogKat"][data-k=""]'); await p.waitForTimeout(600);
  await p.click('.blog-feat'); await p.waitForTimeout(700);
  check('membuka artikel', await p.locator('.blog-title').count() === 1 && await p.locator('.prose h2').count() >= 1);
  check('judul tab mengikuti artikel', (await p.title()).includes('·'));
  await p.click('[data-x="blogBack"]'); await p.waitForTimeout(500);
  check('kembali ke daftar artikel', await p.locator('.blog-feat').count() === 1);

  console.log('CMS (Marketing LSP)');
  await p.click('.topbar [data-go="login"]'); await p.fill('#lg-email', 'marketing.tdn@demo.portallsp.id'); await p.fill('#lg-pass', 'Demo-Pass-2026');
  await p.click('#loginForm button[type=submit]'); await p.waitForTimeout(1500);
  await p.click('.side nav button[data-go-app="blog"]'); await p.waitForTimeout(800);
  check('halaman Blog (CMS) terbuka', /Blog \(CMS\)/.test(await p.locator('.content').innerText()));
  await p.click('[data-edit="new"]'); await p.waitForTimeout(400);
  await p.fill('#editor input[name="judul"]', judul);
  await p.selectOption('#editor select[name="kategori"]', 'Tips Sertifikasi');
  await p.fill('#editor input[name="tags"]', 'uji, browser');
  await p.fill('#editor textarea[name="ringkasan"]', 'Ringkasan dari uji browser.');
  await p.fill('#blog-konten', 'Paragraf pembuka.\n\n');
  await p.click('[data-x="mdIns"][data-m="h2"]'); await p.keyboard.type('Subjudul Uji');
  await p.keyboard.type('\n\n'); await p.click('[data-x="mdIns"][data-m="bold"]');
  await p.keyboard.type('\n\n- poin satu\n- poin dua\n\n<img src=x onerror=alert(1)> teks aman');
  await p.click('[data-x="blogPreview"]'); await p.waitForTimeout(200);
  const pv = p.locator('#blog-preview');
  check('pratinjau merender format', await pv.locator('h2').innerText() === 'Subjudul Uji' && await pv.locator('b').innerText() === 'teks tebal' && await pv.locator('li').count() === 2);
  check('pratinjau tidak mengeksekusi HTML', await pv.locator('img').count() === 0 && /<img src=x/.test(await pv.innerText()));
  await p.selectOption('#editor select[name="status"]', 'terbit');
  await p.click('#editor button[type="submit"]'); await p.waitForTimeout(1200);
  check('editor tetap terbuka untuk sampul setelah simpan', await p.locator('#blog-cover-file').count() === 1);
  const png = path.join(os.tmpdir(), 'sampul-uji.png');
  fs.writeFileSync(png, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'));
  await p.setInputFiles('#blog-cover-file', png);
  await p.click('[data-x="blogCover"]'); await p.waitForTimeout(1000);
  check('sampul tampil di editor', await p.locator('#editor img.blog-cover').count() === 1);
  await p.click('#editor [data-close]'); await p.waitForTimeout(300);
  const row = p.locator('tr', { hasText: judul });
  check('artikel ada di tabel dengan status Terbit', /Terbit/.test(await row.innerText()));
  await p.screenshot({ path: OUT + 'blog-cms.png', fullPage: true });

  console.log('Tautan langsung ?artikel=');
  const href = await row.locator('a', { hasText: 'Lihat' }).getAttribute('href');
  const p2 = await b.newPage({ viewport: { width: 390, height: 844 } });
  p2.on('pageerror', e => errs.push(e.message));
  let alerted = false; p2.on('dialog', d => { alerted = true; d.dismiss(); });
  await p2.goto(BASE + '/' + href.replace('./', ''), { waitUntil: 'networkidle' }); await p2.waitForTimeout(800);
  check('pengguna login tetap di artikel (tidak dialihkan ke dashboard)', (await p2.locator('.blog-title').innerText()) === judul);
  check('isi artikel dirender aman', await p2.locator('.prose h2').innerText() === 'Subjudul Uji' && await p2.locator('.prose img').count() === 0 && !alerted);
  check('sampul tampil di artikel', await p2.locator('.blog-article img.blog-cover').count() === 1);
  check('tanpa scroll horizontal di ponsel', await p2.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await p2.screenshot({ path: OUT + 'blog-artikel-ponsel.png', fullPage: true });
  await p2.click('[data-x="blogTag"][data-tag="browser"]'); await p2.waitForTimeout(700);
  check('klik tag mencari artikel bertag', /Uji Browser Blog/.test(await p2.locator('.content, #root').first().innerText()));
  await p2.close();

  console.log('Moderasi (Admin Platform)');
  const p3 = await b.newPage({ viewport: { width: 1280, height: 900 } });
  p3.on('pageerror', e => errs.push(e.message));
  p3.on('dialog', d => d.type() === 'prompt' ? d.accept('Judul menyesatkan, mohon diperbaiki.') : d.accept());
  await p3.goto(BASE + '/', { waitUntil: 'networkidle' });
  await p3.click('.topbar [data-go="login"]'); await p3.fill('#lg-email', 'superadmin@demo.portallsp.id'); await p3.fill('#lg-pass', 'Demo-Pass-2026');
  await p3.click('#loginForm button[type=submit]'); await p3.waitForTimeout(1500);
  await p3.click('.side nav button[data-go-app="blog"]'); await p3.waitForTimeout(800);
  const r3 = p3.locator('tr', { hasText: judul });
  check('Admin Platform melihat artikel LSP + kolom penerbit', /LSP Teknologi Digital Nusantara/.test(await r3.innerText()));
  await r3.locator('[data-x="blogTurunkan"]').click(); await p3.waitForTimeout(900);
  check('status menjadi Diturunkan', /Diturunkan/.test(await p3.locator('tr', { hasText: judul }).innerText()));
  await p3.locator('tr', { hasText: judul }).locator('[data-act="blog/moderasi"]').click(); await p3.waitForTimeout(900);
  check('dipulihkan kembali', /Terbit/.test(await p3.locator('tr', { hasText: judul }).innerText()));
  await p3.locator('tr', { hasText: judul }).locator('[data-act="blog/hapus"]').click(); await p3.waitForTimeout(900);
  check('artikel dihapus', await p3.locator('tr', { hasText: judul }).count() === 0);
  await p3.close();

  check('tanpa error JavaScript', errs.length === 0, errs.slice(0, 3).join(' | '));
  console.log(`\n${pass} lulus, ${fail} gagal`);
  await b.close();
  process.exit(fail ? 1 : 0);
})();
